baseURL = "https://jibecfed.fedorapeople.org/blog-hugo/"
languageCode = "fr"
DefaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
theme = "slim"
enableMissingTranslationPlaceholders = true

[permalinks]
  articles = "/:year/:month/:title/"

[languages]
[languages.fr]
title = "Démonstration d’Hugo avec mon Blog"
contentDir = "content/fr"
LanguageName = "Français"
weight = 10

[[languages.fr.menu.main]]
  name = "À propos"
  identifier = "contact"
  url = "contact/a_propos/"

[[languages.fr.menu.main]]
  name = "Flux RSS"
  identifier = "rss"
  url = "index.xml"

[[languages.fr.menu.main]]
  name = "Mes articles"
  identifier = "articles"
  url = "articles/"

[languages.en]
title = "Hugo's POC with my Blog"
contentDir = "content/en"
LanguageName = "English"
weight = 20

[[languages.en.menu.main]]
  name = "About"
  identifier = "contact"
  url = "contact/a_propos/"

[[languages.en.menu.main]]
  name = "RSS feed"
  identifier = "rss"
  url = "index.xml"

[[languages.en.menu.main]]
  name = "My articles"
  identifier = "articles"
  url = "articles/"