#!/bin/bash
# Author: Jean-Baptiste Holcroft (jibecfed) <jean-baptiste@holcroft.fr>
# This file produce a po4a config file and run po4a
# po4a update all pot, po and publish content

dir=content # no trailing slash

echo " * TODO: Pull translations from translation platform"

echo "Create pot files"

mkdir -p "l10n/pot/"

echo "Generating french content"

for file in $(find -L $dir -name "*.fr.md" ); do
    dirname=$(dirname "$file")
    path=$(echo "$dirname" | cut -d'/' -f2-2)

    if [ "$dirname" = "$dir" ]; then
        potname="root.pot"
    else
        potname="$path.pot"
    fi

    po4a-gettextize \
    	--format text \
    	--master "$file" \
    	--po "l10n/pot/$potname" \
    	--master-charset "UTF-8" \
    	--option debug markdown
done

echo " * Generate english content"

for file in $( find -L $dir -name "*.fr.md" ); do
    dirname=$(dirname "$file")
    path=$(echo "$dirname" | cut -d'/' -f2-2)

    if [ "$dirname" = "$dir" ]; then
        poname="root.en.po"
    else
        poname="$path.en.po"
    fi
    if [[ -e "l10n/po/$poname" ]]; then
        localized="${file/\.fr\.md/\.en\.md}"
        po4a-updatepo --format text --master "$file" --po "l10n/po/$poname" --master-charset "UTF-8"
        po4a-translate --format text --master "$file" --po "l10n/po/$poname" --master-charset "UTF-8" --localized-charset "UTF-8" --localized "$localized" --option debug markdown --keep 0
    fi
done

echo " * TODO: push updated po files to translation platform"

echo "Done."
